### PR TITLE
Add spree namespace compatibility

### PR DESCRIPTION
**Pull request by kpitn**

### CODE REVIEW

**Comment by citrus** [comment]
Thanks for your contribution! I've pulled this into my local 1.0.x branch and am working on getting the tests to pass again. Once they're all green I'll merge this into master. 

On another note I released spree_essentials v0.40.0.rc1 to rubygems. This version supports spree ~> 1.0.0.rc1.

Thanks again!

-Spencer

**Comment by kpitn** [comment]
I was using your 1.0.x branch of spree_essentials.

But i don't know how to launch the test, what are the command to execute ?

**Comment by citrus** [comment]
The tests are all passing now and I've released v0.3.0.rc1 to rubygems. 

To run the tests `cd spree_essential_cms` then run `bundle exec dummier` to setup your testing environment.
Now run `bundle exec rake` to run the tests. I added more detailed instructions to the readme too..

Let me know if you have any questions!

-Spencer

**Comment by kpitn** [comment]
Thank for your help, i will test this.

**Comment by citrus** [comment]
You're welcome! Let me know how it goes..

**Pull request merged**
