### PR TITLE
fix integration test with page ordering position

### PR DESCRIPTION
**Pull request by sbounmy**
green :thumbsup:

### CODE REVIEW

**Comment by citrus** [comment]
awesome, nice work!

Is this for 1.0.x or 1.1.x?

**Comment by citrus** [comment]
or both haha?

**Comment by sbounmy** [comment]
I've tested only with 1.1.0.rc1 :|

**Comment by sbounmy** [comment]
to test 1.0.x I need downgrade spree_essentials too~

**Comment by citrus** [comment]
we'll have to test against spree 1.0.1 and spree_essentials 0.40.0 for the 1.0.x branch...

**Pull request merged**
