### PR TITLE
meta_search and Ransack

### PR DESCRIPTION
**Pull request by ethier**
Updated Gemfile for spree_sample version 1.1.0.beta (probably a better way to do that). Modified the pages_controller and contents_controller to use the new params `:q` and removed references to metasearch actions.

### CODE REVIEW

**Comment by ethier** [comment]
Looks like spree is dropping the metasearch dependency in 1.1.0. The attached patches appear to resolve the metasearch/ransack issues.

**Comment by ethier** [comment]
There is still something broken. Working on it. `@page = Spree:Page.search` in the index.html.erb file is throwing the following error:

`undefined method`admin_searches_path'`

**Comment by citrus** [comment]
Thanks for this! Before I can merge we'll need to update spree_essentials to work with 1.1.0 as well. 

keep it up!

-Spencer :beer:

**Comment by citrus** [comment]
I've updated spree_essentials to be 1.1.0.rc1 compatible so I'll go ahead and merge this...

**Pull request merged**
